### ISSUE TITLE
Launching app after installing .deb package seems to do nothing

### ISSUE THREAD

**Issue by aadilayub** [fraction/oasis-desktop#1]
I installed oasis via the .deb package.
![image](https://user-images.githubusercontent.com/31581044/76927453-cd176380-6900-11ea-87a3-17d59ab89a28.png)

When I try launching it, nothing happens. It just appears on my dock. When I click on the icon, it disappears.
![Screen record from 2020-03-18 10 17 21](https://user-images.githubusercontent.com/31581044/76928169-87f43100-6902-11ea-8e6b-f64b024e58e5.gif)

It didn't run in the background either, according to my system monitor.
![image](https://user-images.githubusercontent.com/31581044/76928263-c8ec4580-6902-11ea-9dc9-7e54aef49064.png)

**Comment by aadilayub** [comment]
Could it be that my computer got confused about which version of oasis to run, since I have oasis installed via npm and via .deb?

**Comment by georgeowell** [comment]
> Could it be that my computer got confused about which version of oasis to run, since I have oasis installed via npm and via .deb?

One thing you could try is looking in the Oasis .desktop file in either /usr/share/applications/ or ~/.local/share/applications/ and see what it says. This could well be something in this area causing it.

Did you try the appimage or snap?

**Comment by aadilayub** [comment]
I just tried launching from the command-line. Looks like there's an npm module causing the error

```
  oasis No configuration file found at /home/aadil/.config/oasis/default.json, using built-in default values. +0ms
error loading sodium bindings: No native build was found for platform=linux arch=x64 runtime=electron abi=76 uv=1 libc=glibc
falling back to javascript version.

Something went wrong installing the "sharp" module

libvips-cpp.so.42: cannot open shared object file: No such file or directory

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues
```

**Comment by aadilayub** [comment]
> One thing you could try is looking in the Oasis .desktop file in either /usr/share/applications/ or ~/.local/share/applications/ and see what it says. This could well be something in this area causing it.

The .desktop file looks fine to me:

```
[Desktop Entry]
Name=oasis-desktop
Exec=/opt/oasis-desktop/oasis-desktop %U
Terminal=false
Type=Application
Icon=oasis-desktop
StartupWMClass=oasis-desktop
Comment=Desktop installation for Oasis
Categories=Network;
```

> Did you try the appimage or snap?

Not yet!

**Comment by georgeowell** [comment]
> I just tried launching from the command-line. Looks like there's an npm module causing the error
> 
> ```
>   oasis No configuration file found at /home/aadil/.config/oasis/default.json, using built-in default values. +0ms
> error loading sodium bindings: No native build was found for platform=linux arch=x64 runtime=electron abi=76 uv=1 libc=glibc
> falling back to javascript version.
> 
> Something went wrong installing the "sharp" module
> 
> libvips-cpp.so.42: cannot open shared object file: No such file or directory
> 
> - Remove the "node_modules/sharp" directory, run "npm install" and look for errors
> - Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
> - Search for this error at https://github.com/lovell/sharp/issues
> ```

Oh yeh I had this before. I just deleted that directory and ran the install commands again.

**Comment by christianbundy** [comment]
Oh damn, I just saw this!

Are you on AMD64? Maybe we need to remove that as a supported architecture. :confused: Sharp gives us a ton of trouble, maybe we should replace it with [Jimp](https://github.com/oliver-moran/jimp)?

**Comment by aadilayub** [comment]
Nope, not on arm64. This was on amd64

**Comment by christianbundy** [comment]
Oh, oops, I misread that. I'd ask you to test on the latest version, but I think #3 is breaking it.

**Comment by christianbundy** [comment]
Just pushed a [new release](https://github.com/fraction/oasis-desktop/releases/latest), could you test whether this problem is still happening? Thank you!

**Comment by aadilayub** [comment]
It works! 
![image](https://user-images.githubusercontent.com/31581044/79078030-ec968600-7d1e-11ea-8519-7ed23a121436.png)
