### ISSUE TITLE
Appimage cannot open on Gnome+Arch

### ISSUE THREAD

**Issue by TROMsite** [fraction/oasis-desktop#47]
Error:
```
 /home/tio/Applications/oasis-desktop-1.3.0-arm64_d5f87d8891ce4c983fb20931b354dcad.AppImage
[appimage-binfmt-bypass/bin] ERROR: failed to execute patched runtime: Exec format error
```

**Comment by christianbundy** [comment]
Could you post the output of `uname -a` please?

**Comment by TROMsite** [comment]
For sure:
`Linux tio-gl753vd 5.10.26-1-MANJARO #1 SMP PREEMPT Thu Mar 25 16:56:17 UTC 2021 x86_64 GNU/Linux`

**Comment by christianbundy** [comment]
It looks like you're on x86_64 but you're using the AppImage for ARM64.

Could you try `oasis-desktop-1.3.0-x86_64.AppImage`?

**Comment by TROMsite** [comment]
Ah I apologize! No idea how come this happened. I did not pay attention. It works now. Thank you and I am sorry for the annoyance :D.

**Comment by christianbundy** [comment]
No problem at all, thanks for the quick testing!
