### ISSUE TITLE
Launching app after installing .dmg and mac.zip seems to do nothing

### ISSUE THREAD

**Issue by spencerhadley** [fraction/oasis-desktop#5]
I tried both .dmg and mac.zip, and I opened each after allowing unidentified developers, but both simply bounced twice and then stopped, never opening a window (even briefly).

Running MacBook Pro (Retina, 15-inch, Late 2013), Catalina 10.15.4 (19E287)

**Comment by christianbundy** [comment]
Sorry @spencerhadley, that's my fault. My intuition is that this is caused by #3.

**Comment by christianbundy** [comment]
Just pushed a fix, could you try again on the [latest release](https://github.com/fraction/oasis-desktop/releases/latest)? Thanks for all your patience.

**Comment by spencerhadley** [comment]
Yes, that did it! Working great now. Thank you.

**Comment by christianbundy** [comment]
:tada:
